name: Tests

on:
    push:

jobs:

    test-windows:
        name: PHPUnit Tests (Windows 7.1 x86)
        runs-on: windows-latest

        env:
            COMPOSER_ROOT_VERSION: dev-main

        steps:
        -   name: Checkout
            uses: actions/checkout@v2

        -   name: Install binaries
            run: |
                mkdir c:\php
                cd c:\php
                curl.exe -fsL https://github.com/symfony/binary-utils/releases/download/v0.1/php-7.1.3-Win32-VC14-x86.zip -o php.zip
                7z x php.zip -y
                del ./*.zip

                cd ext
                curl.exe -fsL https://github.com/symfony/binary-utils/releases/download/v0.1/php_apcu-5.1.8-7.1-ts-vc14-x86.zip -o php_apcu.zip
                7z x php_apcu.zip -y
                del ./*.zip
                cd ..

                copy php.ini-development php.ini
                echo max_execution_time=1200 >> php.ini
                echo date.timezone="UTC" >> php.ini
                echo memory_limit=-1 >> php.ini
                echo extension_dir=ext >> php.ini
                echo extension=php_openssl.dll >> php.ini

        -   name: Run tests
            run: c:\php\php.exe a.php
