name: Tests

on:
    push:

jobs:

    test:
        name: PHPUnit Tests
        runs-on: windows-latest

        env:
            COMPOSER_ROOT_VERSION: dev-main

        steps:
#            -   name: Cache binaries
#                id: cache-binaries
#                uses: actions/cache@v2
#                with:
#                  path: c:\php
#                  key: ${{ runner.os }}-binaries-${{ hashFiles('**/composer.lock') }}

            -   name: Install binaries
#                if: steps.cache-binaries.outputs.cache-hit != 'true'
                run: |
                  mkdir c:\php
                  cd c:\php
                  curl.exe https://github.com/symfony/binary-utils/releases/download/v0.1/php-7.1.3-Win32-VC14-x86.zip -o php.zip
                  7z x php.zip -y >nul
                  del /Q *.zip
                  cd ext
                  curl.exe https://github.com/symfony/binary-utils/releases/download/v0.1/php_apcu-5.1.8-7.1-ts-vc14-x86.zip -o php_apcu.zip
                  7z x php_apcu.zip -y >nul
                  del /Q *.zip
                  cd ..
                  echo @php %%~dp0composer.phar %%* > composer.bat
                  copy /Y php.ini-development php.ini
                  echo max_execution_time=1200 >> php.ini
                  echo date.timezone="UTC" >> php.ini
                  echo memory_limit=-1 >> php.ini
                  echo extension_dir=ext >> php.ini
                  echo extension=php_openssl.dll >> php.ini
                  echo extension=php_apcu.dll >> php.ini
                  echo apc.enable_cli=1 >> php.ini
                  echo extension=php_intl.dll >> php.ini
                  echo extension=php_mbstring.dll >> php.ini
                  echo extension=php_ldap.dll >> php.ini
                  curl.exe https://github.com/composer/composer/releases/download/1.9.0/composer.phar -o composer.phar
#
#            -   name: Setup PHP
#                uses: shivammathur/setup-php@v2
#                with:
#                    coverage: "none"
#                    extensions: "apcu, intl, mbstring, uuid"
#                    ini-values: "memory_limit=-1, session.gc_probability=0, apc.enable_cli=1"
#                    php-version: "${{ matrix.php }}"
#                    tools: "composer:v2"
#
#            -   name: Install dependencies
#                run: composer --prefer-source --no-progress --ansi install
#
#            -   name: Install phpunit dependencies
#                run: ./vendor/bin/simple-phpunit install
#
#            -   name: Run tests
#                run: ./vendor/bin/simple-phpunit
